### PR TITLE
stripCommands should strip ">>"

### PR DESCRIPTION
**Pull request by jd4564**

### CODE REVIEW

**Comment by Morfent** [comment]
That's not the purpose of ``stripCommands``. ``>>`` appears nowhere in messages received; it appears in console to mark what messages appear. Even if it did appear in the message, it wouldn't show up in ``arg`` in the commands that use it.

**Comment by jd4564** [comment]
In the event a bot has access to eval on a server, any user with access to ``.say`` (or .choose) would be able to use eval through the bot. This function would already strip out /eval and !eval, so why not ``>>``?

**Comment by panpawn** [comment]
Also, >>> is a thing, too.  

The point is that this is a huge vulnerability issue if the bot has console access, as pretty much anyone that has access to the commands jd listed can ultimately take control over the server.  I'm confused why this isn't being corrected ?_?

Also Morfent, could you explain the purpose of ``stripCommands``?

**Comment by Morfent** [comment]
Oh, I see what you're talking about. I thought you were talking about the ``>>`` that appear in browser console at first, not eval. I don't think adding a space in front of all messages from those commands is the best solution though. I'd only add the space if the text starts with /, !, or >>.

**Comment by jd4564** [comment]
I changed it to only add a space if the text starts with ``/``, ``!``, or ``>>``.

**Pull request merged**
