### PR TITLE
Implement .uptime

### PR DESCRIPTION
**Pull request by panpawn**
This is a command to see the uptime that the bot has been running.  This is mostly a maintenance command.

### CODE REVIEW

**Comment by Morfent** [comment]
How would users other than the bot owner find the information this would offer useful? With PS' /uptime command, it's useful for garnering an estimate of when the next server restart will be, which is somewhat important if you care about updates and when some user(s) will be unlocked or unbanned. However, with the bot, I don't see how its uptime would provide any useful information.

**Comment by panpawn** [comment]
It'd be the same as all the other developer bot commands; i.e. - the reload command.  This is really only helpful to the person whose hosting the bot when they want to reload their commands.js.

**Comment by Morfent** [comment]
The bot's host can already tell when they need to reload commands.js because it only needs to be reloaded after the file is edited.

**Comment by codelegend** [comment]
bump

**Comment by Irraquated** [comment]
Just so you know @panpawn the uptime doesn't go past a day, after this it stops working.

**Comment by Morfent** [comment]
Closing this. If anyone has a convincing argument for how this would be a useful command to have, I'll write an implementation myself.

**Pull request closed without merging**
