### PR TITLE
Make all instances of .command in messages match config

### PR DESCRIPTION
**Pull request by RhythmsAreFromVibrations**
.<command> into config.commandcharacter + '<command>' is an example

### CODE REVIEW

**Comment by Morfent** [comment]
It's about time you got past aliases. I trust you've tested this?

**Comment by Morfent** [comment]
Also, please make the pullreq title more descriptive. Changing the commit title to "Make all instances of .command in messages match config" would be more concise as wel

**Comment by Morfent** [comment]
Actually I think I'll just merge this and correct the commit title myself.
Grats on your first merged pullreq here!

**Comment by RhythmsAreFromVibrations** [comment]
Tyvm

**Pull request merged**
