### PR TITLE
add two 'aliases' for .setting

### PR DESCRIPTION
**Pull request by RhythmsAreFromVibrations**
add ``'false': false,`` and ``'true': true`` for if a player does, for example: ``.set <command>, [true/false]``to work the same way as on/off and enable/disable

### CODE REVIEW

**Comment by Morfent** [comment]
Please squash your commits
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by Morfent** [comment]
@RhythmsAreFromVibrations ?

**Comment by codelegend** [comment]
btw, why `true/false`, isn't `on/off` easy enough, and user friendly.
`.set ab, false` does not make much sense.

**Comment by Morfent** [comment]
I meant more about when you'd be able to rebase, not so much what the logic is behind adding these. There's some amount of sense from a programming perspective, since that's what ``on/off`` and ``enable/disable`` sets the command's settings for the room to, just using 1 and 0 in place of true and false to save some space for settings.json. What I question is how many users would think of this firstly as a true and false type of question, instead of "Is the command on or off?" or "Is the command enabled or disabled?", because I've never had anyone try to use ``true/false`` or ask me about adding them as aliases.
Either way, I want to see this squashed to one commit since you've already made a few before. git's absolutely essential for contributing, since certain things like merge conflicts or rebasing cannot be resolved from GitHub.
I don't mind adding more aliases if they make sense, but adding them for the sake of having more just makes them unused properties in ``Commands``. At the rate BoTTT responds to commands, keeping the amount there are to a minimum allows it to handle chat message parsing more quickly. I'm not saying they're bad, but they should be something that users would use.

**Comment by RhythmsAreFromVibrations** [comment]
uh im just going to make a new PR bc this one has two different PRs in it

**Comment by RhythmsAreFromVibrations** [comment]
oh that was you, @Morfent, my bad. Wasn't that one already merged though?

**Comment by Morfent** [comment]
No, don't make a new pull request. R e b a s e y o u r c o m m i t s
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by Morfent** [comment]
None of these were merged.

**Pull request closed without merging**
