### PR TITLE
Source Command

### PR DESCRIPTION
**Pull request by Bryan-0**
Hi, i want to do a pull request for this command, is just a source command i mean if someone want to see the bot source just do .source on pm and bot give the link of github in that case will be https://github.com/TalkTakesTime/Pokemon-Showdown-Bot i hope you like the idea! 

Thanks.

### CODE REVIEW

**Comment by Morfent** [comment]
This isn't a bad idea, but I think you should be checking if ``by`` is in ``config.excepts`` instead of their rank, and .git might be a better name for this than .source.

**Comment by Bryan-0** [comment]
Ohh ok, i update the command. and i think all is correct.

**Comment by Morfent** [comment]
This still doesn't check ``config.excepts`` instead of the rank of the user calling the command. Room owners don't need to be able to broadcast this by default.

**Comment by Bryan-0** [comment]
mm, so i will just put that admins can do it? is that right? or & and ~?

**Comment by Morfent** [comment]
No. There are a few other commands that use what I'm talking about instead of ``this.hasRank``.

**Comment by Morfent** [comment]
If you're not going to add the command, I can write it myself, and leave a comment in the code giving credit to you for the idea. I just don't want to keep this pull request open forever.

**Comment by codelegend** [comment]
@Morfent , looks like it is gonna take forever (already a month)

**Comment by Morfent** [comment]
I've talked to him a couple times after his last comments here. I'll write the command myself.

**Pull request closed without merging**
