### PR TITLE
Make every quotation mark match

### PR DESCRIPTION
**Pull request by RhythmsAreFromVibrations**
- changed all `"`'s into `'`'s
- removed all instances of `&` in places where it was listed more than
once
- moved all `&`'s in front of `#`
- removed both GC commands at sirDonovan's request

### CODE REVIEW

**Comment by Morfent** [comment]
I'd rather keep ``&`` where it is now, since it's technically a higher rank than ``#``.

>``'%@&#&~'``
Now that's just embarrassing on my part.

**Comment by RhythmsAreFromVibrations** [comment]
Oh didn't see this x3

I'll squash ASAP

**Comment by Morfent** [comment]
You can use ``git commit -a --amend`` when you only have changes you want to make to the last commit you made instead of having to use ``git rebase -i HEAD~2``, just so you know.

**Comment by RhythmsAreFromVibrations** [comment]
Sorry, I messed up too much. This isn't even something mandatory, so I'll just close this and fix it in a later PR that has more relevant changes.

**Pull request closed without merging**
