### PR TITLE
Added a new Wi-Fi room command (onlinecloners or ocloners) that fetches ...

### PR DESCRIPTION
**Pull request by Golui**
...the google spreadsheet and prints which users are online. Sends to PMs, unless the caller has regular room broadcast permissions.

### CODE REVIEW

**Comment by Golui** [comment]
Any particular reasons this isn't merged yet?

**Comment by Morfent** [comment]
I still haven't added userlist tracking yet, which this needed before it could be merged iirc. If not I'd just have to reread through the code and make sure there aren't any problems before merging.

**Comment by Golui** [comment]
As I mentioned, the cloner command is a secondary priority and is disabled in this version anyway. What is important now is the scammer list command, which is working.

**Comment by Morfent** [comment]
There's still problems with the commands' syntax here. I'll just make any remaining tweaks needed after merging. If you know how, could you quash your commits? If you can't, I'll do it. I just want to be able to get this closed.

Also, you should comment after pushing commits, since no notifications are sent otherwise.

**Comment by Golui** [comment]
Right. Squashed the commits.

**Comment by Morfent** [comment]
@Golui API keys expire on certain conditions. This didn't work with mine because it had expired. See https://developers.google.com/accounts/docs/OAuth2
I'll need to remove this. Unless you can find a way to access the spreadsheets without having to add half a dozen dependencies, I don't think this would work as a command.

**Pull request merged**
